{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "capv.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "capv.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  ports:
    - name: https
      port: {{ .Values.metrics.port }}
      protocol: TCP
      targetPort: metrics
  selector:
    {{- include "capv.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
{{- end }}
