/*
Copyright 2026 The Verda CAPI Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package bootstrap converts Cluster API bootstrap data into a Verda startup script.
//
// Verda instances take a plain shell script at boot rather than cloud-init
// user-data, while the kubeadm bootstrap provider produces a #cloud-config
// document. This package translates the subset of cloud-config that the
// kubeadm bootstrap provider emits (bootcmd, write_files, runcmd) into bash,
// in the same spirit as the Cluster API Docker provider.
package bootstrap

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"path"
	"sort"
	"strings"

	"sigs.k8s.io/yaml"
)

const cloudConfigHeader = "#cloud-config"

// LogPath is where the generated script records its output on the instance.
const LogPath = "/var/log/capi-bootstrap.log"

// cloudConfig is the subset of cloud-config understood by this package.
// Unknown top-level keys are collected and reported, not silently dropped.
type cloudConfig struct {
	BootCmd    []command   `json:"bootcmd,omitempty"`
	WriteFiles []writeFile `json:"write_files,omitempty"`
	RunCmd     []command   `json:"runcmd,omitempty"`
}

var knownKeys = map[string]bool{"bootcmd": true, "write_files": true, "runcmd": true}

type writeFile struct {
	Path        string `json:"path"`
	Content     string `json:"content"`
	Encoding    string `json:"encoding,omitempty"`
	Owner       string `json:"owner,omitempty"`
	Permissions string `json:"permissions,omitempty"`
	Append      bool   `json:"append,omitempty"`
}

// command is a cloud-init command: either a shell string or an argv list.
type command []string

func (c *command) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err == nil {
		*c = command{s}
		return nil
	}
	var list []string
	if err := json.Unmarshal(data, &list); err != nil {
		return fmt.Errorf("command must be a string or a list of strings: %w", err)
	}
	*c = command(list)
	return nil
}

// shell renders the command as a bash line.
func (c command) shell() string {
	if len(c) == 1 {
		return c[0]
	}
	quoted := make([]string, 0, len(c))
	for _, arg := range c {
		quoted = append(quoted, shellQuote(arg))
	}
	return strings.Join(quoted, " ")
}

// Result is the generated startup script plus anything that could not be translated.
type Result struct {
	Script string
	// Unsupported lists cloud-config top-level keys that were present in the
	// input but are not translated (for example users, ntp, mounts).
	Unsupported []string
}

// Placeholders substituted before conversion. Verda has no instance metadata
// service, so the cloud-init jinja variables that Cluster API templates
// conventionally use for the node hostname are resolved here instead.
var hostnamePlaceholders = []string{
	"{{ ds.meta_data.hostname }}",
	"{{ ds.meta_data.local_hostname }}",
	"{{ds.meta_data.hostname}}",
	"{{ds.meta_data.local_hostname}}",
}

// ToStartupScript converts cloud-config bootstrap data into a bash startup script.
// Data that is already a shell script (starts with #!) is returned unchanged.
// hostname replaces the cloud-init hostname placeholders in the data.
func ToStartupScript(data []byte, hostname string) (*Result, error) {
	for _, placeholder := range hostnamePlaceholders {
		data = bytes.ReplaceAll(data, []byte(placeholder), []byte(hostname))
	}
	trimmed := bytes.TrimSpace(data)
	if bytes.HasPrefix(trimmed, []byte("#!")) {
		return &Result{Script: string(data)}, nil
	}
	if !isCloudConfig(trimmed) {
		return nil, fmt.Errorf("bootstrap data is neither a shell script nor %s; ignition and other formats are not supported", cloudConfigHeader)
	}

	var raw map[string]json.RawMessage
	if err := yaml.Unmarshal(trimmed, &raw); err != nil {
		return nil, fmt.Errorf("parsing cloud-config: %w", err)
	}
	var cfg cloudConfig
	if err := yaml.Unmarshal(trimmed, &cfg); err != nil {
		return nil, fmt.Errorf("parsing cloud-config: %w", err)
	}

	res := &Result{}
	for key := range raw {
		if !knownKeys[key] {
			res.Unsupported = append(res.Unsupported, key)
		}
	}
	sort.Strings(res.Unsupported)

	var b strings.Builder
	b.WriteString("#!/bin/bash\n")
	b.WriteString("# Generated by cluster-api-provider-verda from Cluster API bootstrap data. Do not edit.\n")
	b.WriteString("set -euo pipefail\n")
	fmt.Fprintf(&b, "exec > >(tee -a %s) 2>&1\n", LogPath)
	b.WriteString("echo \"[capi-bootstrap] starting $(date -Is)\"\n")
	for _, key := range res.Unsupported {
		fmt.Fprintf(&b, "echo \"[capi-bootstrap] warning: cloud-config key %q is not supported on Verda and was ignored\"\n", key)
	}

	if len(cfg.BootCmd) > 0 {
		b.WriteString("\n# bootcmd\n")
		for _, c := range cfg.BootCmd {
			b.WriteString(c.shell())
			b.WriteByte('\n')
		}
	}

	if len(cfg.WriteFiles) > 0 {
		b.WriteString("\n# write_files\n")
		for i, f := range cfg.WriteFiles {
			if err := writeFileScript(&b, i, f); err != nil {
				return nil, err
			}
		}
	}

	if len(cfg.RunCmd) > 0 {
		b.WriteString("\n# runcmd\n")
		for _, c := range cfg.RunCmd {
			b.WriteString(c.shell())
			b.WriteByte('\n')
		}
	}

	b.WriteString("\necho \"[capi-bootstrap] finished $(date -Is)\"\n")
	res.Script = b.String()
	return res, nil
}

// isCloudConfig reports whether data carries the #cloud-config header. The
// kubeadm bootstrap provider precedes it with a "## template: jinja" line.
func isCloudConfig(data []byte) bool {
	for _, line := range bytes.SplitN(data, []byte("\n"), 4) {
		if bytes.Equal(bytes.TrimSpace(line), []byte(cloudConfigHeader)) {
			return true
		}
	}
	return false
}

// writeFileScript emits the shell needed to materialise one write_files entry.
// Content is always transported base64-encoded so that arbitrary bytes never
// collide with heredoc delimiters or shell syntax.
func writeFileScript(b *strings.Builder, idx int, f writeFile) error {
	if f.Path == "" {
		return fmt.Errorf("write_files[%d]: path is required", idx)
	}
	content, err := decodeContent(f.Content, f.Encoding)
	if err != nil {
		return fmt.Errorf("write_files[%d] (%s): %w", idx, f.Path, err)
	}
	// gzip content is left compressed and inflated on the instance.
	decoder := "base64 -d"
	if isGzip(f.Encoding) {
		decoder = "base64 -d | gunzip"
	}
	redirect := ">"
	if f.Append {
		redirect = ">>"
	}
	delim := fmt.Sprintf("__CAPI_FILE_%d__", idx)

	fmt.Fprintf(b, "mkdir -p %s\n", shellQuote(path.Dir(f.Path)))
	fmt.Fprintf(b, "%s %s %s <<'%s'\n", decoder, redirect, shellQuote(f.Path), delim)
	b.WriteString(wrapBase64(base64.StdEncoding.EncodeToString(content)))
	fmt.Fprintf(b, "%s\n", delim)
	if f.Permissions != "" {
		fmt.Fprintf(b, "chmod %s %s\n", shellQuote(f.Permissions), shellQuote(f.Path))
	}
	if f.Owner != "" {
		fmt.Fprintf(b, "chown %s %s\n", shellQuote(f.Owner), shellQuote(f.Path))
	}
	return nil
}

// decodeContent returns the raw bytes to ship for a write_files entry. Plain
// and base64 content are decoded; gzip variants are returned still compressed.
func decodeContent(content, encoding string) ([]byte, error) {
	switch strings.ToLower(strings.TrimSpace(encoding)) {
	case "", "text/plain":
		return []byte(content), nil
	case "b64", "base64", "gz+b64", "gzip+base64", "gz+base64", "gzip+b64":
		decoded, err := base64.StdEncoding.DecodeString(strings.TrimSpace(content))
		if err != nil {
			return nil, fmt.Errorf("decoding base64 content: %w", err)
		}
		return decoded, nil
	case "gz", "gzip":
		return []byte(content), nil
	default:
		return nil, fmt.Errorf("unsupported content encoding %q", encoding)
	}
}

func isGzip(encoding string) bool {
	return strings.HasPrefix(strings.ToLower(strings.TrimSpace(encoding)), "gz")
}

// wrapBase64 splits a base64 string into 76-column lines, which base64 -d accepts.
func wrapBase64(s string) string {
	const width = 76
	var b strings.Builder
	for len(s) > width {
		b.WriteString(s[:width])
		b.WriteByte('\n')
		s = s[width:]
	}
	b.WriteString(s)
	b.WriteByte('\n')
	return b.String()
}

// shellQuote single-quotes s for safe use as a bash word.
func shellQuote(s string) string {
	if s == "" {
		return "''"
	}
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
