## Append samples of your project ##
resources:
- infrastructure_v1beta1_verdacluster.yaml
- infrastructure_v1beta1_verdamachine.yaml
- infrastructure_v1beta1_verdamachinetemplate.yaml
- infrastructure_v1beta1_verdaclustertemplate.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
