/*
Copyright 2026 The Verda CAPI Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package loadbalancer manages the provider-owned haproxy instance that fronts
// a cluster's control plane. Verda has no managed load balancer, so the
// provider runs its own: a small instance with haproxy in TCP mode whose
// backend list is kept in sync with the control plane machines over SSH.
package loadbalancer

import (
	"crypto/ed25519"
	"crypto/rand"
	"encoding/base64"
	"encoding/pem"
	"fmt"
	"slices"
	"strings"

	"golang.org/x/crypto/ssh"
)

// Port is the port haproxy listens on and forwards to on the backends.
const Port = 6443

// ConfigPath is where haproxy.cfg lives on the load balancer instance.
const ConfigPath = "/etc/haproxy/haproxy.cfg"

// Config renders haproxy.cfg for the given backend IPs. Backends are sorted
// so the output is stable and comparable.
func Config(backends []string) string {
	sorted := slices.Clone(backends)
	slices.Sort(sorted)

	var b strings.Builder
	b.WriteString(`# Managed by cluster-api-provider-verda. Do not edit.
global
    log /dev/log local0
    maxconn 4096

defaults
    mode tcp
    log global
    option tcplog
    option dontlognull
    timeout connect 10s
    timeout client 1h
    timeout server 1h

frontend kube-apiserver
    bind *:6443
    default_backend kube-apiserver

backend kube-apiserver
    balance roundrobin
    option tcp-check
    default-server inter 5s fall 3 rise 2
`)
	for i, ip := range sorted {
		fmt.Fprintf(&b, "    server cp-%d %s:%d check\n", i, ip, Port)
	}
	return b.String()
}

// Keys holds the SSH material for one load balancer: a client key pair the
// provider uses to log in, and the host key pair installed on the instance so
// the provider can verify it without trust-on-first-use.
type Keys struct {
	ClientPrivateKey []byte // PEM, OpenSSH format
	ClientPublicKey  []byte // authorized_keys line
	HostPrivateKey   []byte // PEM, OpenSSH format
	HostPublicKey    []byte // known_hosts style public key line
}

// GenerateKeys creates fresh ed25519 client and host key pairs.
func GenerateKeys() (*Keys, error) {
	clientPriv, clientPub, err := generateKeyPair("cluster-api-provider-verda")
	if err != nil {
		return nil, fmt.Errorf("generating client key: %w", err)
	}
	hostPriv, hostPub, err := generateKeyPair("")
	if err != nil {
		return nil, fmt.Errorf("generating host key: %w", err)
	}
	return &Keys{ClientPrivateKey: clientPriv, ClientPublicKey: clientPub, HostPrivateKey: hostPriv, HostPublicKey: hostPub}, nil
}

func generateKeyPair(comment string) (privPEM, pubLine []byte, err error) {
	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		return nil, nil, err
	}
	block, err := ssh.MarshalPrivateKey(priv, comment)
	if err != nil {
		return nil, nil, err
	}
	sshPub, err := ssh.NewPublicKey(pub)
	if err != nil {
		return nil, nil, err
	}
	return pem.EncodeToMemory(block), ssh.MarshalAuthorizedKey(sshPub), nil
}

// StartupScript renders the first-boot script for the load balancer instance:
// it installs haproxy, installs the provider's client key and the pre-generated
// host key, and starts haproxy with the initial (possibly empty) backend list.
func StartupScript(keys *Keys, backends []string) string {
	var b strings.Builder
	b.WriteString(`#!/bin/bash
# Generated by cluster-api-provider-verda for the control plane load balancer. Do not edit.
set -euo pipefail
exec > >(tee -a /var/log/capi-loadbalancer.log) 2>&1
echo "[capi-lb] starting $(date -Is)"

export DEBIAN_FRONTEND=noninteractive
for i in 1 2 3 4 5; do apt-get update && apt-get install -y haproxy && break || sleep 10; done

# SSH: provider client key and pre-generated host key.
mkdir -p /root/.ssh && chmod 700 /root/.ssh
`)
	fmt.Fprintf(&b, "base64 -d >> /root/.ssh/authorized_keys <<'__CAPI_EOF__'\n%s\n__CAPI_EOF__\n", base64.StdEncoding.EncodeToString(keys.ClientPublicKey))
	b.WriteString("chmod 600 /root/.ssh/authorized_keys\n")
	fmt.Fprintf(&b, "base64 -d > /etc/ssh/ssh_host_ed25519_key <<'__CAPI_EOF__'\n%s\n__CAPI_EOF__\n", base64.StdEncoding.EncodeToString(keys.HostPrivateKey))
	fmt.Fprintf(&b, "base64 -d > /etc/ssh/ssh_host_ed25519_key.pub <<'__CAPI_EOF__'\n%s\n__CAPI_EOF__\n", base64.StdEncoding.EncodeToString(keys.HostPublicKey))
	b.WriteString(`chmod 600 /etc/ssh/ssh_host_ed25519_key
chmod 644 /etc/ssh/ssh_host_ed25519_key.pub
systemctl restart ssh || systemctl restart sshd

# haproxy
`)
	fmt.Fprintf(&b, "base64 -d > %s <<'__CAPI_EOF__'\n%s\n__CAPI_EOF__\n", ConfigPath, base64.StdEncoding.EncodeToString([]byte(Config(backends))))
	b.WriteString(`haproxy -c -f ` + ConfigPath + `
systemctl enable haproxy
systemctl restart haproxy
echo "[capi-lb] finished $(date -Is)"
`)
	return b.String()
}

// UpdateCommand is the remote command that installs a new haproxy.cfg read
// from stdin, validates it and reloads haproxy without dropping connections.
const UpdateCommand = "set -e; cat > " + ConfigPath + ".new && haproxy -c -f " + ConfigPath + ".new >/dev/null && mv " + ConfigPath + ".new " + ConfigPath + " && systemctl reload haproxy"
